### ISSUE TITLE
"dogs" constructors don't seem to work when the dogs constructor is on a base class

### ISSUE THREAD

**Issue by point-source** [helightdev/dogs#4]
**Affected packages**
- dogs_core
- dogs_generator

**Describe the bug**
When using a base class that has an initializer list, the generation of serializers for an inheriting class fails with this error:
```
Exception: Serializable constructors must only reference instance fields: #0      structurizeConstructor (package:dogs_generator/analyze/structurize.dart:125:7)
#1      ConverterBuilder.generateForClass (package:dogs_generator/builders/converter_builder.dart:82:28)
#2      ConverterBuilder.generateSubject (package:dogs_generator/builders/converter_builder.dart:355:17)
#3      _ServiceAdapterServiceBuilder.build (package:lyell_gen/src/subject.dart:127:19)
<asynchronous suspension>
#4      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:83:7)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#6      scopeLogAsync.<anonymous closure> (package:build/src/builder/logging.dart:32:40)
<asynchronous suspension>
```

**To Reproduce**
1. Create a Dart project with these classes:
```dart
import 'package:uuid/uuid.dart';
import 'package:dogs_core/dogs_core.dart';

abstract class Base {
  final String id;

  Base({String? id}) : id = id ?? const Uuid().v4();

  Base.dogs(this.id);
}

@serializable
class User extends Base with Dataclass<User> {
  final String username;

  User({
    super.id,
    required this.username,
  });
}

```
2. Run the build_runner
3. Observe the error

**Expected behavior**
There ought to be a way to handle this case, though I don't know exactly what the best way is.

**Comment by helightdev** [comment]
Forgot to add support for super fields, I'm on it

**Comment by helightdev** [comment]
> Forgot to add support for super fields, I'm on it

I originally wrote this part of the serializer when super formal parameter relatively new (or not even implemented, I can't remember fully), so I basically just forgot to add support for it. Didn't need much change though.

**Comment by helightdev** [comment]
The cleaner way would still be not generating the uuid inside the model class, but specifying it when you create a new instance of the object. This would be the "advised" way to handle this problem with dogs. The model files are meant to stay relatively clean and decoupled from the rest of the code, being inherently static in their nature.

**Comment by point-source** [comment]
Thanks for the quick update!

The reason I do it the way I do is because I don't want the class variable to be nullable. That said, I could use your example but modify it by using "late" to workaround that issue.

As for the model files remaining static and decoupled, I tend to agree as I continue to move further into functional programming. That said, I really wish that making standalone factory methods was as convenient as adding constructors. Having to write out all the field types by hand rather than using "this." is pretty annoying. Open to new ideas for streamlining cases like this.

**Comment by helightdev** [comment]
I just thought about this issue a bit and I actually agree that the rules for constructors might be a bit too restrictive. I will think about a way to make factories and non-field parameters work with the system. This will take a bit of time to fully implement though.

As for the is field, you could also name it $id, make it nullable and add an getter for accessing with '!'.

**Comment by helightdev** [comment]
My current idea would be taking the name of the parameter and looking up the class members if a field or getter for this name exists. About nullability,the constructor parameter will dictate it. Annotations will still have to be placed on the getter or field, annotations on constructors are ugly.

**Comment by helightdev** [comment]
```dart
@serializable
class InitializersModel with Dataclass<InitializersModel> {

  final String id;

  InitializersModel(String? id) : id = id ?? "default";

  factory InitializersModel.variant0() {
    return InitializersModel(null);
  }

  factory InitializersModel.variant1() {
    return InitializersModel("id1");
  }
}

@serializable
class ConstructorBodyModel with Dataclass<ConstructorBodyModel>{

  late String id;
  late String data;

  ConstructorBodyModel(String? id, String data) {
    this.id = id ?? "default";
    this.data = data;
  }

  factory ConstructorBodyModel.variant0() {
    return ConstructorBodyModel(null, "data0");
  }

  factory ConstructorBodyModel.variant1() {
    return ConstructorBodyModel("id1", "data1");
  }
}

@serializable
class GetterModel with Dataclass<GetterModel> {

  late String id;
  String? _buffer;

  GetterModel(String? id, String data)  {
    this.id = id ?? "default";
    _buffer = data;
  }

  @PropertyName(r"$data")
  String get data => "$_buffer";

  factory GetterModel.variant0() {
    return GetterModel(null, "data0");
  }

  factory GetterModel.variant1() {
    return GetterModel("id1", "data1");
  }
}
```

Next release will satisfy those special cases where getters and non-formal parameters are used

**Comment by helightdev** [comment]
Implemented in
```dart
dogs_core: ^8.0.1
```

**Comment by point-source** [comment]
Beautiful, thanks!

**Comment by helightdev** [comment]
Feel free to reach out if you encounter anything else you are missing from the package. Really appreciate it.
